use AutoTrade;
go
--create table Brands
--(
--Id int identity primary key not null,
--Name nvarchar(50) not null
--);
--go


INSERT INTO [AutoTrade].[dbo].[Brands]
           ([Name])
     VALUES
           ('Acura')
           ,('Alfa Romeo')
           ,('Aptera')
           ,('Aston Martin')
           ,('Audi')
           ,('Austin')
           ,('BMW')
           ,('Bentley')
           ,('Bugatti')
           ,('Buick')
           ,('Cadillac')
           ,('Chevrolet')
           ,('Chrysler')
           ,('Citroën')
           ,('Corbin')
           ,('Daewoo')
           ,('Daihatsu')
           ,('Defender')
           ,('Dodge')
           ,('Eagle')
           ,('FIAT')
           ,('Fairthorpe')
           ,('Ferrari')
           ,('Fiat')
           ,('Fillmore')
           ,('Foose')
           ,('Ford')
           ,('GMC')
           ,('Geo')
           ,('HUMMER')
           ,('Hillman')
           ,('Holden')
           ,('Honda')
           ,('Hummer')
           ,('Hyundai')
           ,('Infiniti')
           ,('Isuzu')
           ,('Jaguar')
           ,('Jeep')
           ,('Jensen')
           ,('Kia')
           ,('Lamborghini')
           ,('Land Rover')
           ,('Lexus')
           ,('Lincoln')
           ,('Lotus')
           ,('Lotus Cars')
           ,('MG')
           ,('MINI')
           ,('Maserati')
           ,('Maybach')
           ,('Mazda')
           ,('McLaren')
           ,('Mercedes-Benz')
           ,('Mercury')
           ,('Merkur')
           ,('Mitsubishi')
           ,('Morgan')
           ,('Nissan')
           ,('Oldsmobile')
           ,('Panoz')
           ,('Peugeot')
           ,('Plymouth')
           ,('Pontiac')
           ,('Porsche')
           ,('Ram')
           ,('Rambler')
           ,('Renault')
           ,('Rolls-Royce')
           ,('Saab')
           ,('Saturn')
           ,('Scion')
           ,('Shelby')
           ,('Smart')
           ,('Spyker')
           ,('Spyker Cars')
           ,('Studebaker')
           ,('Subaru')
           ,('Suzuki')
           ,('Tesla')
           ,('Toyota')
           ,('Volkswagen')
           ,('Volvo');
GO


