use AutoTrade;
go
--create table Brands
--(
--Id int identity primary key not null,
--Name nvarchar(50) not null
--);
--go

--INSERT INTO [AutoTrade].[dbo].[Brands]
--           ([Name])
--     VALUES
--           (8192,'Acura')
--           ,(8193,'Alfa Romeo')
--           ,(8194,'Aptera')
--           ,(8195,'Aston Martin')
--           ,(8196,'Audi')
--           ,(8197,'Austin')
--           ,(8198,'BMW')
--           ,(8204,'Bentley')
--           ,(8205,'Bugatti')
--           ,(8206,'Buick')
--           ,(8207,'Cadillac')
--           ,(8208,'Chevrolet')
--           ,(8209,'Chrysler')
--           ,(8211,'Citroën')
--           ,(8212,'Corbin')
--           ,(8213,'Daewoo')
--           ,(8214,'Daihatsu')
--           ,(8215,'Defender')
--           ,(8216,'Dodge')
--           ,(8217,'Eagle')
--           ,(8218,'FIAT')
--           ,(8219,'Fairthorpe')
--           ,(8220,'Ferrari')
--           ,(8221,'Fiat')
--           ,(8222,'Fillmore')
--           ,(8223,'Foose')
--           ,(8224,'Ford')
--           ,(8226,'GMC')
--           ,(8227,'Geo')
--           ,(8228,'HUMMER')
--           ,(8229,'Hillman')
--           ,(8230,'Holden')
--           ,(8231,'Honda')
--           ,(8232,'Hummer')
--           ,(8233,'Hyundai')
--           ,(8234,'Infiniti')
--           ,(8235,'Isuzu')
--           ,(8236,'Jaguar')
--           ,(8237,'Jeep')
--           ,(8238,'Jensen')
--           ,(8239,'Kia')
--           ,(8240,'Lamborghini')
--           ,(8242,'Land Rover')
--           ,(8243,'Lexus')
--           ,(8244,'Lincoln')
--           ,(8245,'Lotus')
--           ,(8246,'Lotus Cars')
--           ,(8247,'MG')
--           ,(8248,'MINI')
--           ,(8249,'Maserati')
--           ,(8250,'Maybach')
--           ,(8251,'Mazda')
--           ,(8253,'McLaren')
--           ,(8254,'Mercedes-Benz')
--           ,(8255,'Mercury')
--           ,(8256,'Merkur')
--           ,(8257,'Mitsubishi')
--           ,(8260,'Morgan')
--           ,(8261,'Nissan')
--           ,(8262,'Oldsmobile')
--           ,(8263,'Panoz')
--           ,(8264,'Peugeot')
--           ,(8265,'Plymouth')
--           ,(8266,'Pontiac')
--           ,(8267,'Porsche')
--           ,(8269,'Ram')
--           ,(8270,'Rambler')
--           ,(8271,'Renault')
--           ,(8272,'Rolls-Royce')
--           ,(8273,'Saab')
--           ,(8274,'Saturn')
--           ,(8275,'Scion')
--           ,(8276,'Shelby')
--           ,(8277,'Smart')
--           ,(8278,'Spyker')
--           ,(8279,'Spyker Cars')
--           ,(8280,'Studebaker')
--           ,(8281,'Subaru')
--           ,(8282,'Suzuki')
--           ,(8284,'Tesla')
--           ,(8285,'Toyota')
--           ,(8286,'Volkswagen')
--           ,(8287,'Volvo');
--GO


INSERT INTO [AutoTrade].[dbo].[Brands]
           ([Name])
     VALUES
           ('Acura')
           ,('Alfa Romeo')
           ,('Aptera')
           ,('Aston Martin')
           ,('Audi')
           ,('Austin')
           ,('BMW')
           ,('Bentley')
           ,('Bugatti')
           ,('Buick')
           ,('Cadillac')
           ,('Chevrolet')
           ,('Chrysler')
           ,('Citroën')
           ,('Corbin')
           ,('Daewoo')
           ,('Daihatsu')
           ,('Defender')
           ,('Dodge')
           ,('Eagle')
           ,('FIAT')
           ,('Fairthorpe')
           ,('Ferrari')
           ,('Fiat')
           ,('Fillmore')
           ,('Foose')
           ,('Ford')
           ,('GMC')
           ,('Geo')
           ,('HUMMER')
           ,('Hillman')
           ,('Holden')
           ,('Honda')
           ,('Hummer')
           ,('Hyundai')
           ,('Infiniti')
           ,('Isuzu')
           ,('Jaguar')
           ,('Jeep')
           ,('Jensen')
           ,('Kia')
           ,('Lamborghini')
           ,('Land Rover')
           ,('Lexus')
           ,('Lincoln')
           ,('Lotus')
           ,('Lotus Cars')
           ,('MG')
           ,('MINI')
           ,('Maserati')
           ,('Maybach')
           ,('Mazda')
           ,('McLaren')
           ,('Mercedes-Benz')
           ,('Mercury')
           ,('Merkur')
           ,('Mitsubishi')
           ,('Morgan')
           ,('Nissan')
           ,('Oldsmobile')
           ,('Panoz')
           ,('Peugeot')
           ,('Plymouth')
           ,('Pontiac')
           ,('Porsche')
           ,('Ram')
           ,('Rambler')
           ,('Renault')
           ,('Rolls-Royce')
           ,('Saab')
           ,('Saturn')
           ,('Scion')
           ,('Shelby')
           ,('Smart')
           ,('Spyker')
           ,('Spyker Cars')
           ,('Studebaker')
           ,('Subaru')
           ,('Suzuki')
           ,('Tesla')
           ,('Toyota')
           ,('Volkswagen')
           ,('Volvo');
GO


