--use master;
--go

--create database AutoTrade
--on
--(
--name=AutoTrade_dat,
--filename="d:\autotrade.mdf",
--size=10,
--maxsize=50,
--filegrowth=5
--)
--log on
--(
--name=AutoTrade_log,
--filename="d:\autotrade.ldf",
--size=5MB,
--maxsize=25MB,
--filegrowth=5MB
--);
--go


----create trigger ChangePriceEvent 
----on Model
----for insert, update, delete
----not for replication
----as
----set nocount on;

----declare @change_type as varchar(10)
----declare @count as int

----set @change_type = 'inserted'
----	select @count = COUNT(*) FROM DELETED
----	if @count > 0
----		begin
----			set @change_type = 'deleted'
----				select @count = COUNT(*) from INSERTED
----				if @Count > 0
----					set @change_type = 'updated'
----		end;
----if @change_type='inserted' or @change_type='updated'
----	begin
----		if not exists(
----				select *
----				from dbo.PriceHistory as PH, inserted as i
----				where PH.IdModel=i.Id and
----					PH.ChangeDate=getdate() and
----					PH.Price=i.Price)
----			insert into PriceHistory(IdModel,Price)
----			select Id, Price
----			from inserted 
----	end;
----else
----	begin
----		delete from dbo.PriceHistory
----		where IdModel=(select Id from deleted)
----	end;
----go