//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AutoTrade.Domain.Concrete
{
    public partial class AutoModel
    {
        public AutoModel()
        {
            this.Vehicles = new HashSet<Vehicle>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdBrand { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Vehicle> Vehicles { get; set; }
        public virtual Brand Brand { get; set; }
    }
    
}
