//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace AutoTrade.Domain.Concrete
{
    public partial class Brand
    {
        public Brand()
        {
            this.AutoModels = new HashSet<AutoModel>();
        }
    
        [ScaffoldColumn(false)]
        //[HiddenInput(DisplayValue=false)]
        public int Id { get; set; }

        [Required(ErrorMessage="Please, enter a brand name")]
        public string Name { get; set; }
    
        public virtual ICollection<AutoModel> AutoModels { get; set; }
    }
    
}
