//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AutoTrade.Domain.Concrete
{
    public partial class PricesHistory
    {
        public int Id { get; set; }
        public Nullable<int> IdVehicle { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public decimal Price { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
    
}
